### ISSUE TITLE
Ganache reports "Uh Oh... That's a bug." Blockchain process exited prematurely with code '7', due to signal 'null'.

### ISSUE THREAD

**Issue by bingtimren** [trufflesuite/ganache#284]
![image](https://user-images.githubusercontent.com/2824513/35020421-f3173da8-fb66-11e7-8028-c10152b6e71d.png)

 

## Expected Behavior

well, should not report a bug and make my test lose connection

## Current Behavior

I don't know if it's related but I just developed a very very simple standard token, just a child contract of the StandardToken from Zeppelin framework. And I'm also running the tests in the Zeppelin framework, then this happens from time to time.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 1.0.2
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): don't know. I just downloaded the app image from website
* Server type and version:
[9:22:36 AM] Starting server with configuration: {"hostname":"127.0.0.1","mnemonic":"candy maple cake sugar pudding cream honey rich smooth crumble sweet treat","network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[]}
[9:22:36 AM] Ganache started successfully!
[9:22:36 AM] Waiting for requests...
* Operating System and version: Ubuntu desktop 17.04
* Link to your project:

**Comment by benjamincburns** [comment]
Hi @bingtimren - thanks for reporting this. Unfortunately, there really isn't much information for me to go on here.  Can you please use the "Raise GitHub Issue" in the bug dialog that pops up to grab the application log, and then modify your description to include that info?

**Comment by bingtimren** [comment]
I clicked that button, my Chrome browser pop-up, but then nothing happens. If you let me know how to find the log in the file system I'm happy to upload it here. 
Cheers!

**Comment by benjamincburns** [comment]
I had that problem as well - it was due to enabling the flag `chrome://flags#enable-site-per-process` in response to the meltdown bug. If you've enabled that, disable it temporarily and you'll be able to see the log.

Unfortunately the log isn't written out to disk anywhere, so apart from building the project yourself this is the best way to get it.

**Comment by bingtimren** [comment]
Well it's not enabled...... let me see if I can find ways to reproduce it. It seems random but maybe not....

**Comment by benjamincburns** [comment]
@bingtimren if it occurs randomly, I'm going to bet a dollar that it's trufflesuite/ganache-cli#417 or one of the other race conditions that's now fixed in the latest `develop` branch.

I'm in the process of publishing prerelease builds with this fix in place. I'll see if I can't get the Linux one up there in just a few minutes.

**Comment by bingtimren** [comment]
Yes, it's random. Even I restart Ganache (clear all blocks) every time and execute truffle migrate --reset; right before truffle test, I get different results. 

I have a feeling this relates to gas limit. When things are not as expected, I receive "Error: The contract code couldn't be stored, please check your gas amount."

However I still cannot give you more information. Chrome popup without anything further happen.

**Comment by benjamincburns** [comment]
@bingtimren let me know if you manage to get any more information, otherwise I'm going to clear this one from my list for now.

Also if you learn what it is about your environment that prevents the bug modal from opening a new pre-filled issue, please raise a new issue for that!

If it helps any, most issues reported via the bug dialog are reported numerous times, so chances are good that the issue which is triggering this for you is already found and fixed.

**Comment by bingtimren** [comment]
Please close this one. I don't have anything substantial to add.

**Comment by BelfordZ** [comment]
![image](https://user-images.githubusercontent.com/1787231/36710460-ff72421e-1b32-11e8-8b61-d1aaeeecf2e9.png)
@benjamincburns freshly checked out master branch and `npm install`.
