### ISSUE TITLE
Error: sender doesn't have enough funds to send tx

### ISSUE THREAD

**Issue by LuigiCerone** [trufflesuite/ganache#836]
The method eth_sendRawTransaction gives me the following error:
```
eth_sendRawTransaction
   > {
   >   "id": 1572373240,
   >   "jsonrpc": "2.0",
   >   "params": [
   >     "0xf8af808504a817c800827d00943019069e52896a789f85fc2e49e50d60c112b84a80b8447bbac7620000000000000000000000000000000000000000000000000000000000084a0200000000000000000000000094d4215ac1ef2a38a5bd421b33eedfa4a0115dfd8602c91dc1e484a0f6ed496f4b5b0b80d1316a396e4fb28e1e1c3f3544786677f050ff7d5b5bd1f9a04d549396433e0026b82c750fb69556969f1b6336bed79fe5815b453217799987"
   >   ],
   >   "method": "eth_sendRawTransaction"
   > }
 <   {
 <     "id": 1572373240,
 <     "jsonrpc": "2.0",
 <     "error": {
 <       "message": "sender doesn't have enough funds to send tx. The upfront cost is: 640000000000000 and the sender's account only has: 0",
 <       "code": -32000,
 <       "data": {
 <         "stack": "Error: sender doesn't have enough funds to send tx. The upfront cost is: 640000000000000 and the sender's account only has: 0\n    at /usr/lib/node_modules/ganache-cli/build/cli.node.js:134:583610\n    at /usr/lib/node_modules/ganache-cli/build/cli.node.js:2:82429\n    at d (/usr/lib/node_modules/ganache-cli/build/cli.node.js:2:71063)\n    at /usr/lib/node_modules/ganache-cli/build/cli.node.js:2:71091\n    at _e (/usr/lib/node_modules/ganache-cli/build/cli.node.js:2:71122)\n    at /usr/lib/node_modules/ganache-cli/build/cli.node.js:2:71180\n    at sa (/usr/lib/node_modules/ganache-cli/build/cli.node.js:2:82405)\n    at Object.Sa [as series] (/usr/lib/node_modules/ganache-cli/build/cli.node.js:2:84555)\n    at g.e.exports [as runTx] (/usr/lib/node_modules/ganache-cli/build/cli.node.js:134:583054)\n    at /usr/lib/node_modules/ganache-cli/build/cli.node.js:134:586512\n    at /usr/lib/node_modules/ganache-cli/build/cli.node.js:2:80454\n    at d (/usr/lib/node_modules/ganache-cli/build/cli.node.js:2:71063)\n    at /usr/lib/node_modules/ganache-cli/build/cli.node.js:2:71091\n    at Dt (/usr/lib/node_modules/ganache-cli/build/cli.node.js:2:80524)\n    at Object.<anonymous> (/usr/lib/node_modules/ganache-cli/build/cli.node.js:2:71180)\n    at /usr/lib/node_modules/ganache-cli/build/cli.node.js:134:586344\n    at /usr/lib/node_modules/ganache-cli/build/cli.node.js:2:82429\n    at d (/usr/lib/node_modules/ganache-cli/build/cli.node.js:2:71063)\n    at o (/usr/lib/node_modules/ganache-cli/build/cli.node.js:2:70967)\n    at /usr/lib/node_modules/ganache-cli/build/cli.node.js:2:70761\n    at /usr/lib/node_modules/ganache-cli/build/cli.node.js:2:82490\n    at /usr/lib/node_modules/ganache-cli/build/cli.node.js:2:67819",
 <         "name": "Error"
 <       }
 <     }
 <   }
```

I get this error only if I try to sign a contract transaction by using `web3.eth.accounts.signTransaction();` docs [here](https://web3js.readthedocs.io/en/1.0/web3-eth.html#signtransaction) and then send the raw with `web3.eth.sendSignedTransaction();.` 
Instead, if I use `contractInstance.methods.myMethods(params).send({..}) ` the transaction is correctly send to the contract.

With the followig code I can send the transaction with no errors.

```
let nonce = await web3.eth.getTransactionCount(web3.eth.defaultAccount);
            console.log("Nonce value is: " + nonce);

            let result = await UnityContract.methods.addLand(newUnity._landParcel, newUnity._ownerAddress).send({
                from: web3.eth.defaultAccount,
                nonce: web3.utils.toHex(++nonce),
                gas: web3.utils.toHex(300000)
            });
            console.log(result);
```

Where the result contains the transaction:
```
{
	"blockHash": "0x73ce0ae172d27f8ea065626b27c68db2972a6e03858d726783a6e676015c9e36",
	"blockNumber": 19,
	"contractAddress": null,
	"cumulativeGasUsed": 138823,
	"events": {
		"Add": {..}
	},
	"gasUsed": 138823,
	"logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000001000000080000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
	"status": true,
	"transactionHash": "0x5c5804d46df219e433e4c837a57702a1825fce231a7e33788f6fd4e7d2d435f2",
	"transactionIndex": 0
}
```

If instead I "manually" sign the transaction with this code:

```
let encodedMethod = UnityContract.methods.addLand(newUnity._landParcel, newUnity._ownerAddress).encodeABI();
            console.log("EncodedMethod is: " + encodedMethod);
            
            console.log("Default account is:" + web3.eth.defaultAccount);
            let val = await web3.eth.getBalance(web3.eth.defaultAccount);
            console.log("Fund is:" + val);
            let transactionToSign = {
                gas: web3.utils.toHex(32000),
                gasPrice: '0x4a817c800',
                to: contractAddress,
                data: encodedMethod,
                nonce: web3.utils.toHex(++nonce)
            };

            let signedTransaction = await  web3.eth.accounts.signTransaction(transactionToSign, web3.eth.defaultAccount);
            let result = await web3.eth.sendSignedTransaction(signedTransaction.rawTransaction);
            console.log(result);
```

I get the error of "sender doesn't have enough funds to send tx" even though the web3.eth.defaultAccount is a testing account with 100 ETH in it.
 
I've read the [release highlights](https://github.com/trufflesuite/ganache/releases/tag/v1.2.1) of ganache-cli version 6.1.6 and I think that first highlight is talking about this problem. So I'm using version 6.1.6.

> ganache-cli --version
Ganache CLI v6.1.6 (ganache-core: 2.1.5)

And

> npm list -g ganache-cli
/usr/lib
└── ganache-cli@6.1.6 

## Your Environment
Web3js: v1.0.0 
Truffle version: 6.1.6
Metamask version: 4.8.0
OS: Debian Linux 9

**Comment by mallapurbharat** [comment]
@LuigiCerone  I'm facing this same issue with Ganache 1.2.0 (and 1.2.1) GUI version, along with another issue of nonce mismatch.
Have you tried using Ganache-cli 1.1.0? I found that both my issues got resolved once I downgraded to the earlier version.

**Comment by LuigiCerone** [comment]
Hi @mallapurbharat , thanks for your reply. 
Are you talking abount Ganache-cli 1.1.0 or Ganache gui 1.1.0? Because I cannot see v.1.1.0 or ganache-cli neither in [https://github.com/trufflesuite/ganache-cli/tags](url) nor in npm.

> npm view ganache-cli versions --json
[
  "0.0.1",
  "6.0.3",
  "6.1.0-beta.0",
  "6.1.0-beta.1",
  "6.1.0-beta.2",
  "6.1.0-beta.3",
  "6.1.0-beta.4",
  "6.1.0",
  "6.1.2",
  "6.1.3",
  "6.1.4",
  "6.1.5",
  "6.1.6",
  "7.0.0-beta.0"
]

I've also tried a fresh new install of ganache-cli and Metamask but I still got the "sender doesn't have enough fund to send tx".

**Comment by seesemichaelj** [comment]
@luigicerone he's talking about Ganache UI. The corresponding cli version would be 6.1.4. 6.1.5 introduced the bug he's referring to, but it was fixed in 6.1.6

I'll take a look at this today

**Comment by bingozwb** [comment]
I got the same issues on 1.2.0, and 1.1.0 GUI would be fine

**Comment by seesemichaelj** [comment]
I'm closing this due to inactivity. This was fixed in `ganache-cli@6.1.6` and `ganache@1.2.1`. Please find the appropriate releases [here](https://github.com/trufflesuite/ganache-cli/releases) and [here](https://github.com/trufflesuite/ganache/releases) respectively.

Thanks!

**Comment by ish3lan** [comment]
I added more funded accounts, and it worked (i.e. `-a 40`) when running `ganache-cli.`

**Comment by SirPhemmiey** [comment]
That's not sufficient

**Comment by SirPhemmiey** [comment]
I am still having this issue. 

My current Ganache CLI version is v6.6.0

**Comment by 3centsFR** [comment]
I am still having this issue.
My current Ganache CLI version is v6.7.0

**Comment by nicholasjpaterno** [comment]
@SirPhemmiey and @3centsFR I'd be happy to take a look.  Can you point me towards a minimum viable test to recreate this issue?  As a reference, this is one of our test cases where we sign and send a transaction: https://github.com/trufflesuite/ganache-core/blob/13bff0109b3b2b69823ae6e2e76ae493896a2353/test/gas/gas.js#L277

**Comment by abuaesh** [comment]
I also got the same error. I was able to solve it by changing the mnemonic in my truffle-config.js to match the mnemonic given by Ganache CLI

**Comment by sfl0r3nz05** [comment]
I got the same error, deploying ganache on docker. @abuaesh, how do you pass mnemonic to ganache provider?

![image](https://user-images.githubusercontent.com/6643905/97642143-c29b7b80-1a44-11eb-9399-4e4b167685b8.png)
![image](https://user-images.githubusercontent.com/6643905/97642110-ae577e80-1a44-11eb-819c-5ba53e6a9b89.png)

**Comment by sfl0r3nz05** [comment]
Hi, I have solved via: const provider = ganache.provider({mnemonic: process.env.GANACHE_CLI});

**Comment by AuroraLantean** [comment]
In Hardhat, setting the gas and gasPrice solves it for me!
hardhat: {
gas: 678880,
gasPrice: 1000000,
}
